//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQProjects.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LINQProjects.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на aleksandr
        ///nikolaj
        ///ivan
        ///sergej
        ///vladimir
        ///mikhail
        ///vasilij
        ///aleksej
        ///andrej
        ///dmitrij
        ///viktor
        ///yurij
        ///petr
        ///anatolij
        ///pavel
        ///igor
        ///evgenij
        ///oleg
        ///valerij
        ///vitalij
        ///grigorij
        ///fedor
        ///boris
        ///gennadij
        ///leonid
        ///konstantin
        ///vyacheslav
        ///georgij
        ///denis
        ///valentin
        ///maksim
        ///vadim
        ///roman
        ///ilya
        ///ruslan
        ///stepan
        ///semen
        ///anton
        ///eduard
        ///stanislav
        ///yakov
        ///arkadij
        ///vladislav
        ///artem
        ///kirill
        ///egor
        ///artur
        ///marat
        ///albert
        ///lev
        ///ildar
        ///iosif
        ///timofej
        ///rinat
        ///rustam
        ///veniamin
        ///rustem
        ///radik
        ///aleksand
        ///ramil
        ///afanasij
        ///nikita
        ///filipp
        ///efim
        ///azat
        ///timur
        ///ajrat
        ///kuzma
        ///petr
        ///german
        ///robert
        ///aleksanr
        ///inno [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ivanov
        ///ivanova
        ///kuznetsov
        ///smirnov
        ///popov
        ///petrov
        ///vasilev
        ///smirnova
        ///kuznetsova
        ///kozlov
        ///vasileva
        ///petrova
        ///novikov
        ///sokolov
        ///popova
        ///volkov
        ///fedorov
        ///mikhajlov
        ///semenov
        ///pavlov
        ///morozov
        ///zajtsev
        ///stepanov
        ///andreev
        ///egorov
        ///nikitin
        ///mikhajlova
        ///zakharov
        ///makarov
        ///alekseev
        ///kozlova
        ///fedorova
        ///sokolova
        ///yakovlev
        ///kovalenko
        ///nikolaev
        ///solovev
        ///bondarenko
        ///pavlova
        ///kovalev
        ///lebedev
        ///shevchenko
        ///vorobev
        ///andreeva
        ///romanov
        ///novikova
        ///semenova
        ///sergeev
        ///grigorev
        ///kiselev
        ///morozova
        ///volkova
        ///kravchenko
        ///baranov
        ///kuzmin
        ///alekseeva
        ///stepanova
        ///frolov
        ///melnikov
        ///borisov
        ///ego [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
    }
}
